# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, default='no-category', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제품명')),
                ('image', models.ImageField(blank=True, upload_to='stuff/images/%Y/%m/%d/')),
                ('desc', models.CharField(max_length=500, verbose_name='설명')),
                ('status', models.CharField(blank=True, choices=[('a', 'available'), ('u', 'unavailable')], default='a', help_text='Stuff availability', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilyeo.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(verbose_name='대여일')),
                ('return_date', models.DateTimeField(verbose_name='반납일')),
                ('status', models.CharField(blank=True, choices=[('d', 'Default'), ('r', 'Request'), ('a', 'Accept'), ('c', 'Completed')], default='d', help_text='Rental availability', max_length=1)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeo.stuff', verbose_name='제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대여자')),
            ],
        ),
    ]
