# Generated by Django 4.0.5 on 2022-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilyeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='fee',
            field=models.IntegerField(default=1, verbose_name='대여료'),
            preserve_default=False,
        ),
    ]
