# Generated by Django 4.0.5 on 2022-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilyeo', '0002_stuff_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='total_fee',
            field=models.IntegerField(default=1, verbose_name='대여료 총액'),
            preserve_default=False,
        ),
    ]
